# Generated by Django 4.2.1 on 2023-05-17 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_time',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 17)),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
