# Generated by Django 4.2.1 on 2023-05-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0002_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
