# Generated by Django 4.2.1 on 2023-05-17 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0002_remove_match_date_time_match_date_match_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 17, 19, 59, 59, 203153, tzinfo=datetime.timezone.utc)),
        ),
    ]
