# Generated by Django 4.2.1 on 2023-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0004_alter_match_date_alter_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
