# Generated by Django 4.2.1 on 2023-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0005_alter_match_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='friends',
            field=models.ManyToManyField(related_name='my_friends', to='linkupapi.golfer'),
        ),
        migrations.AlterField(
            model_name='match',
            name='message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
