# Generated by Django 4.2.1 on 2023-05-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0007_golfer_matches_match_golfers_alter_golfer_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfermatch',
            name='is_initiator',
        ),
    ]
