# Generated by Django 4.2.1 on 2023-05-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0008_remove_golfermatch_is_initiator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holescore',
            name='golfer_match',
        ),
        migrations.AddField(
            model_name='holescore',
            name='golfer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_scores', to='linkupapi.golfer'),
        ),
        migrations.AddField(
            model_name='holescore',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_player_scores', to='linkupapi.match'),
        ),
    ]
