# Generated by Django 4.2.1 on 2023-05-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkupapi', '0009_remove_holescore_golfer_match_holescore_golfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holescore',
            name='notes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
